name: Build
on: 
  repository_dispatch:

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - { sys: mingw64, arch: 64bit, whl_tag: win_amd64, env: x86_64 }
          - { sys: mingw32, arch: 32bit, whl_tag: win32, env: i686 }
    
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{matrix.sys}}
          install: >-
            base-devel
            mingw-w64-${{matrix.env}}-toolchain
            mingw-w64-${{matrix.env}}-python
            mingw-w64-${{matrix.env}}-python-pip

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: pyinstaller/pyinstaller
          ref: v6.11.1

      - name: Build bootloader
        run: |
          cd bootloader
          python waf distclean all --target-arch=${{matrix.arch}} --gcc

      - name: Build packages
        run: |
          python -m pip install wheel
          python setup.py sdist bdist_wheel

      - name: List ./dist
        run: |
          ls ./dist

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: ./dist
      #     destination_dir: ${{matrix.env}}
      #     keep_files: true

      - name: Move dist/pyinstaller-6.3.0-py3-none-any.whl to pyinstaller-6.3.0-py3-none-(win32|win64).whl
        run: mv dist/pyinstaller-6.3.0-py3-none-any.whl pyinstaller-6.3.0-py3-none-${{matrix.whl_tag}}.whl

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: PyInstaller
          files: pyinstaller-6.3.0-py3-none-${{matrix.whl_tag}}.whl
